### ISSUE TITLE
Update Corretto Q4 2022 release

### ISSUE THREAD

**Issue by caojoshua** [johanjanssen/ChocolateyPackages#175]
Hi, I'm from the Corretto team at Amazon. We have the following releases as of yesterday:

* https://github.com/corretto/corretto-8/releases
* https://github.com/corretto/corretto-11/releases
* https://github.com/corretto/corretto-17/releases
* https://github.com/corretto/corretto-18/releases

Can we get them updated in Chocolatey?

**Comment by johanjanssen** [comment]
Hi @caojoshua thanks for the notification, I've just pushed the Chocolatey packages.

**Comment by caojoshua** [comment]
Should I see the new changes in https://community.chocolatey.org/packages?q=corretto?

The version numbers are still the same from the previous release. I also noticed that I had a typo in the original request. I had corretto-18. Edited it to say corretto-19

**Comment by johanjanssen** [comment]
It looks like they're in some scanning stage, you can see it here: https://community.chocolatey.org/profiles/JohanJanssen

Or look at the version history of a specific package: https://community.chocolatey.org/packages/corretto8jdk/8.352#versionhistory

**Comment by johanjanssen** [comment]
Today I got a notification that the packages were approved. So you can now officially use them.
